services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      OLLAMA_HOST: http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb


  frontend:
    build:
      context: ./client/web
      dockerfile: Dockerfile
      args:
        PUBLIC_CLIENT_SIDE_QUEBYS_API_BASE_URL: http://localhost:8000/api
        PUBLIC_SERVER_SIDE_QUEBYS_API_BASE_URL: http://backend:8000/api
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      PORT: 5000
      ORIGIN: http://localhost:5000


  telegram-bot:
    build:
      context: ./client/telegram-bot
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    env_file:
      - .env
    environment:
      BASE_URL_BACKEND: http://backend:8000


  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: